import { CommandDef, CommandResult } from './types';

const BOX = {
  tl: '╔', tr: '╗', bl: '╚', br: '╝',
  h: '═', v: '║',
  ml: '╠', mr: '╣',
};

function box(title: string, lines: string[]): string {
  const maxLen = Math.max(title.length + 4, ...lines.map(l => l.length + 4));
  const width = maxLen;
  const hr = BOX.h.repeat(width - 2);
  const top = `${BOX.tl}${hr}${BOX.tr}`;
  const mid = `${BOX.ml}${hr}${BOX.mr}`;
  const bot = `${BOX.bl}${hr}${BOX.br}`;
  const titleLine = `${BOX.v} ${title.padEnd(width - 3)} ${BOX.v}`;
  const bodyLines = lines.map(l => `${BOX.v} ${l.padEnd(width - 3)} ${BOX.v}`);
  return [top, titleLine, mid, ...bodyLines, bot].join('\n');
}

export const portfolioCommands: CommandDef[] = [
  {
    name: 'whoami',
    category: 'Portfolio',
    description: 'Display current user info. Use -v for verbose.',
    appMenuMode: 'terminal',
    handler: (args: string[]): CommandResult => {
      if (args.includes('-v')) {
        return box('USER PROFILE', [
          'Name     : Ritinder Singh',
          'Handle   : ritinder',
          'Role     : Backend Developer · Flutter · Python',
          'Location : India',
          'Stack    : Python · FastAPI · Flask · Dart · Flutter',
          'DB       : PostgreSQL · Redis · MySQL · MongoDB',
          'DevOps   : Docker · GitHub Actions · Nginx · Linux',
          'Email    : for.ritindersingh@gmail.com',
          'GitHub   : github.com/ritinder',
          'LinkedIn : linkedin.com/in/ritinder-singh',
        ]);
      }
      return 'ritinder';
    },
  },
  {
    name: 'about',
    category: 'Portfolio',
    description: 'Learn about Ritinder Singh',
    appMenuMode: 'gui',
    guiWindowType: 'about',
    handler: (): CommandResult => {
      return [
        '',
        '  ╔══════════════════════════════════════════════════════╗',
        '  ║              ABOUT RITINDER SINGH                   ║',
        '  ╚══════════════════════════════════════════════════════╝',
        '',
        '  Name     : Ritinder Singh',
        '  Role     : Backend Developer · Flutter Developer',
        '  Location : India 🇮🇳',
        '',
        '  Bio:',
        '  ─────────────────────────────────────────────────────',
        '  I\'m a passionate backend developer who loves building',
        '  scalable, production-ready systems using Python.',
        '  I specialize in FastAPI and Flask microservices,',
        '  PostgreSQL database design, and async task queues.',
        '',
        '  On the mobile side, I craft beautiful cross-platform',
        '  apps with Flutter — from smooth animations to complex',
        '  state management with Bloc and Firebase integration.',
        '',
        '  I believe in clean code, solid architecture, and',
        '  shipping things that actually work.',
        '  ─────────────────────────────────────────────────────',
        '',
        '  Type "skills" to see my tech stack.',
        '  Type "projects" to see what I\'ve built.',
        '',
      ].join('\n');
    },
  },
  {
    name: 'skills',
    category: 'Portfolio',
    description: 'View technical skills and stack',
    appMenuMode: 'gui',
    guiWindowType: 'skills',
    handler: (): CommandResult => {
      return [
        '',
        '  ╔══════════════════════════════════════════════════════╗',
        '  ║                  TECHNICAL SKILLS                   ║',
        '  ╚══════════════════════════════════════════════════════╝',
        '',
        '  Languages',
        '  ─────────',
        '  Python · Dart · JavaScript · SQL · Bash',
        '',
        '  Backend',
        '  ───────',
        '  FastAPI · Flask · Django REST · PostgreSQL',
        '  Redis · Celery · Docker · Kubernetes',
        '',
        '  Mobile',
        '  ──────',
        '  Flutter · Firebase · Bloc · Provider · REST APIs',
        '',
        '  DevOps',
        '  ──────',
        '  Docker · GitHub Actions · Nginx · Linux · AWS basics',
        '',
        '  Databases',
        '  ─────────',
        '  PostgreSQL · MySQL · SQLite · Redis · MongoDB',
        '',
      ].join('\n');
    },
  },
  {
    name: 'projects',
    category: 'Portfolio',
    description: 'View portfolio projects',
    appMenuMode: 'gui',
    guiWindowType: 'projects',
    handler: (): CommandResult => {
      return [
        '',
        '  ╔══════════════════════════════════════════════════════╗',
        '  ║                 PORTFOLIO PROJECTS                  ║',
        '  ╚══════════════════════════════════════════════════════╝',
        '',
        '  [1] QuickMart Backend',
        '  ─────────────────────',
        '  FastAPI + PostgreSQL e-commerce backend with JWT auth,',
        '  Redis caching, and Celery async tasks.',
        '  Tech: FastAPI · PostgreSQL · Redis · Celery · Docker',
        '  → github.com/ritinder/quickmart-api',
        '',
        '  [2] TaskFlow',
        '  ─────────────',
        '  Flutter productivity app with offline sync, Firebase',
        '  backend, and Bloc state management.',
        '  Tech: Flutter · Firebase · Bloc · Dart',
        '  → github.com/ritinder/taskflow',
        '',
        '  [3] DevMetrics',
        '  ───────────────',
        '  Real-time developer dashboard with WebSocket streaming',
        '  and PostgreSQL analytics engine.',
        '  Tech: FastAPI · WebSocket · PostgreSQL · React',
        '  → github.com/ritinder/devmetrics',
        '',
        '  [4] PyBot',
        '  ──────────',
        '  Telegram bot framework in Python with plugin system',
        '  and Redis session storage.',
        '  Tech: Python · Redis · Telegram API · asyncio',
        '  → github.com/ritinder/pybot',
        '',
      ].join('\n');
    },
  },
  {
    name: 'contact',
    category: 'Portfolio',
    description: 'Get contact information',
    appMenuMode: 'gui',
    guiWindowType: 'contact',
    handler: (): CommandResult => {
      return [
        '',
        '  ╔══════════════════════════════════════════════════════╗',
        '  ║                  CONTACT INFO                       ║',
        '  ╚══════════════════════════════════════════════════════╝',
        '',
        '  Email    : for.ritindersingh@gmail.com',
        '  GitHub   : github.com/ritinder',
        '  LinkedIn : linkedin.com/in/ritinder-singh',
        '  Twitter  : @ritinder_dev',
        '',
        '  I\'m always open to interesting projects and',
        '  conversations. Don\'t hesitate to reach out!',
        '',
      ].join('\n');
    },
  },
  {
    name: 'achievements',
    category: 'Portfolio',
    description: 'View achievements and certifications',
    appMenuMode: 'gui',
    guiWindowType: 'achievements',
    handler: (): CommandResult => {
      return [
        '',
        '  ╔══════════════════════════════════════════════════════╗',
        '  ║                   ACHIEVEMENTS                      ║',
        '  ╚══════════════════════════════════════════════════════╝',
        '',
        '  🏆 Built & deployed 4+ production APIs serving 1000+ users',
        '     Year: 2024',
        '',
        '  🥇 Won 2nd place at regional hackathon (24-hour sprint)',
        '     Project: Real-time collaborative code editor',
        '     Year: 2023',
        '',
        '  📜 Certified: Docker & Kubernetes Fundamentals',
        '     Issued by: KodeKloud · 2024',
        '',
        '  ⭐ 100+ GitHub stars across open source projects',
        '     Community contributor to FastAPI ecosystem',
        '     Year: 2024',
        '',
      ].join('\n');
    },
  },
  {
    name: 'availability',
    category: 'Portfolio',
    description: 'Check current availability for work',
    appMenuMode: 'terminal',
    handler: (): CommandResult => {
      return [
        '',
        '  ┌─────────────────────────────────────────────────┐',
        '  │  STATUS: OPEN TO OPPORTUNITIES                  │',
        '  └─────────────────────────────────────────────────┘',
        '',
        '  Looking for: Backend / Flutter roles',
        '  Preference : Remote (open to hybrid)',
        '  Notice     : Available immediately',
        '',
        '  Interested? → for.ritindersingh@gmail.com',
        '',
      ].join('\n');
    },
  },
  {
    name: 'now',
    category: 'Portfolio',
    description: 'What Ritinder is currently working on',
    appMenuMode: 'terminal',
    handler: (): CommandResult => {
      return [
        '',
        '  ╔══════════════════════════════════════════════╗',
        '  ║            CURRENTLY WORKING ON              ║',
        '  ╚══════════════════════════════════════════════╝',
        '',
        '  → Learning Rust (systems programming & WebAssembly)',
        '  → Building QuickMart v2 with microservices arch',
        '  → Contributing to FastAPI open source ecosystem',
        '  → Writing a blog about backend engineering patterns',
        '',
        '  Last updated: March 2025',
        '',
      ].join('\n');
    },
  },
  {
    name: 'testimonials',
    category: 'Portfolio',
    description: 'Read what people say about Ritinder',
    appMenuMode: 'terminal',
    handler: (): CommandResult => {
      return [
        '',
        '  ╔══════════════════════════════════════════════════════╗',
        '  ║                   TESTIMONIALS                      ║',
        '  ╚══════════════════════════════════════════════════════╝',
        '',
        '  "Ritinder delivered a rock-solid FastAPI backend for',
        '   our startup. Clean code, great documentation, and',
        '   shipped on time. Highly recommended."',
        '                            — Arjun M., Startup Founder',
        '',
        '  "The Flutter app he built for us is buttery smooth.',
        '   Attention to detail is exceptional — animations,',
        '   offline sync, everything just works."',
        '                            — Priya K., Product Manager',
        '',
        '  "Great collaborator. He takes ownership of problems',
        '   and always thinks about scalability first."',
        '                            — Dev Team Lead, TechCorp',
        '',
      ].join('\n');
    },
  },
  {
    name: 'resume',
    category: 'Portfolio',
    description: 'View or download resume',
    appMenuMode: 'gui',
    guiWindowType: 'resume',
    handler: (): CommandResult => {
      return [
        '',
        '  ┌─────────────────────────────────────────────────┐',
        '  │  RESUME — Ritinder Singh                        │',
        '  └─────────────────────────────────────────────────┘',
        '',
        '  Download: /resume.pdf',
        '  Or open the Resume window for the full view.',
        '',
        '  Quick summary:',
        '  • 3+ years backend development (Python ecosystem)',
        '  • FastAPI, Flask, Django REST Framework',
        '  • Flutter mobile development (iOS + Android)',
        '  • PostgreSQL, Redis, Docker, CI/CD pipelines',
        '',
      ].join('\n');
    },
  },
  {
    name: 'blog',
    category: 'Portfolio',
    description: 'Read blog posts',
    appMenuMode: 'gui',
    guiWindowType: 'blog',
    handler: (): CommandResult => {
      return [
        '',
        '  ╔══════════════════════════════════════════════════════╗',
        '  ║                    BLOG POSTS                       ║',
        '  ╚══════════════════════════════════════════════════════╝',
        '',
        '  [1] "FastAPI vs Flask: When to use which?"',
        '      A practical guide for backend developers.',
        '      → Coming soon...',
        '',
        '  [2] "Flutter Bloc: The definitive guide"',
        '      State management patterns that scale.',
        '      → Coming soon...',
        '',
        '  [3] "Docker in Production: Lessons learned"',
        '      Real-world tips from shipping containers.',
        '      → Coming soon...',
        '',
        '  Blog is under construction. Stay tuned!',
        '  Follow: github.com/ritinder for updates.',
        '',
      ].join('\n');
    },
  },
];
